### ISSUE TITLE
Add factory pools to Curve

### ISSUE THREAD

**Issue by adamazad** [levelkdev/swapr-sdk#81]
**Description**

Curve v2 has a factory contract to deploy new Curve pools. 

**Acceptance Criteria**

- `CurveTrade` can find and get quotes from Curve v2 pools

**Comment by berteotti** [comment]
In order to fetch the desired pool which we can trade using Curve we must use this Registry method [`find_pool_for_coins`](https://curve.readthedocs.io/registry-registry.html#Registry.find_pool_for_coins).

The method receives token `_from`, token `_to` and index `i`. As there is more than 1 pool by swap pair, the index is necessary to specify which pool we want to use.

The only solution I found to know which index maps to a certain pool is to loop over `find_pool_for_coins` method until reaching a `Zero Address`.

**Comment by adamazad** [comment]
Hey Leo, that's the implementation used here:

https://github.com/levelkdev/swapr-sdk/blob/6835310065865c419ea546002515bcc9e34f5c74/src/entities/trades/curve/contracts/pools.ts#L31-L99

However, Messari created subgraphs for all Curve pools. This subgraph can be used to obtain the coins list - they're ordered. That will help.

**Comment by berteotti** [comment]
As I'm looking into Messari subgraphs, it looks like impossible to query Curve Lending pools. Should we move forward with Base pools support only?

**Comment by adamazad** [comment]
That's alright. We have Lending Pools here:

https://github.com/levelkdev/swapr-sdk/blob/b5b2356ccd5df4881c0e2d47b7ecfab7a568967d/src/entities/trades/curve/pools/pools.ts#L88-L95

Curve v2, and this issue, is mainly concerning the pools deployed by the factory contracts.

**Comment by berteotti** [comment]
It seems there is a way to find pools deployed by the factory contract in the subgraph, but not sure if they have all the info we need. Pool input tokens seems unordered and there is no way to get pool "coins". It also looks that factory deployed pools aren't considered Base pools, although they have similar interfaces. 

Here is a print of the most useful info I found. 
![image](https://user-images.githubusercontent.com/23079677/174646453-b8862585-1272-4138-8670-831c24725268.png)

And here is the query I made.

![image](https://user-images.githubusercontent.com/23079677/174646549-b0d3941b-753b-4010-a817-b057a03c88ef.png)

**Comment by Mi-Lan** [comment]
@adamazad @berteotti Hey I was looking into this what about using their api they have specific apy just for factory pools...https://api.curve.fi/api/getPools/ethereum/factory

**Comment by Mi-Lan** [comment]
@adamazad So the current aributrum one subgraph is down https://thegraph.com/hosted-service/subgraph/messari/curve-finance-arbitrum . And not sure how reliable it is... 

- I think its more reliable to use their api since thats how they fetch it for their front-end also
![Screenshot 2022-07-05 at 17 49 57](https://user-images.githubusercontent.com/33226956/177367542-eff99a52-4dc7-40a0-bc14-d3b94fa38ab4.png)
they even have api for fetching subgraph data??

- this is api they use to fetch factory pools heres the documentation for the api they have specific api just for factory pools https://github.com/curvefi/curve-api/blob/main/endpoints.md

![Uploading Screenshot 2022-07-05 at 17.50.42.png…]()
